
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssd-jvh
  namespace: opensaas-argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/OpsMx/enterprise-ssd.git"
      targetRevision: HEAD
      path: charts/ssd
      helm:
        valueFiles:
          - "$values/tenants/jvh/values.yaml"
    - repoURL: https://github.com/Tanmaykaturi/opensaas-argocd
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: jvh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
